el_library_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from el_library import views
import tagulous.views
from el_library.models import Material


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/?', views.signup, name='signup'),
    url(r'^login/?', views.login, name='login'),
    url(r'^date/?', views.date, name='date'),
    url(r'^admin/', admin.site.urls),
    url(r'^tags/', views.tags, name='tags'),
    url(r'^lk/$', views.lk, name='lk'),
    url(r'^control/$', views.control, name='control'),
    url(r'^control/materials/$', views.control_materials, name='control_materials'),
    url(r'^control/rubrik/$', views.control_rubrik, name='control_rubrik'),
    url(r'^control/access/$', views.control_access, name='control_access'),
    url(r'^control/access/(?P<group_id>\d+)?/', views.control_access_view, name='control_access_view'),
    url(r'^control/access/create/', views.control_access_create, name='control_access_create'),
    url(r'^control/rubrikedit/$', views.control_rubrik_edit, name='control_rubrik_edit'),
    url(r'^control/tags/$', views.control_tags, name='control_tags'),
    url(r'^control/tags/(?P<tag_id>\d+)?/', views.control_tag, name='control_tag'),
    url(r'^control/users/$', views.control_users, name='control_users'),
    url(r'^control/materials/edit/$', views.control_materials_edit, name='control_materials_edit'),
    url(r'^control/materials/approve/(?P<material_id>\d+)/(?P<status>\d+)?/',
            views.control_approve_material, name='control_approve_material'),
    url(r'^control/block/user/(?P<user_id>\d+)/(?P<type_b>\d+)?/',
            views.control_block_user, name='control_block_user'),
    url(r'^rubrik/', views.rubrik, name='rubrik'),
    url(r'^lk/my/$', views.my, name='my'),
    url(r'^catalog/', views.catalog, name='catalog'),
    url(r'^search/$', views.search_form, name='search_form'),
    url(r'^collections/$', views.collections, name='collections'),
    url(r'^collections/(?P<collection_id>\d+)?/', views.collection, name='collection'),
    url(r'^collections/create/', views.create_collection, name='create_collection'),
    url(r'^logout/?', views.logout, name='logout'),
    url(r'^search/(?P<query>[\w|\W]+)?/', views.search, name='search'),
    url(r'^searchtitle/(?P<query>[\w|\W]+)?/', views.search_title, name='search_title'),
    url(r'^searchtag/(?P<query>[\w|\W]+)?/', views.search_tag, name='search_tag'),
    url(r'^lk/edit/(?P<material_id>\d+)?/', views.edit_material, name='edit'),
    url(r'^lk/(?P<action>\w+)/(?P<material_id>\d+)?/', views.delete_material, name='delete'),
    url(r'^addcollection/(?P<material_id>\w+)/(?P<collection_id>\d+)?/', views.add_to_collection, name='addcollection'),
    url(r'^delfrom/(?P<material_id>\w+)/(?P<collection_id>\d+)?/', views.del_from_collection, name='addcollection'),
    url(r'^control/add/$', views.add_material, name='add_material'),
    url(
        r'^api/tags/$',
        tagulous.views.autocomplete,
        {'tag_model': Material},
        name='material_tag_autocomplete',
    ),
    url(r'^material/(?P<material_id>\d+)?/?', views.material, name='mterial'),

]

el_library/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import tagulous.models


class Profile(models.Model):
    nickname = models.CharField(max_length=20)
    fio = models.CharField(max_length=50)


class Tags(models.Model):
    tag = models.CharField(max_length=25)
    is_deleted = models.IntegerField(default=0)


class Access(models.Model):
    name = models.CharField(max_length=25)
    access_level = models.IntegerField(default=0)
    is_deleted = models.IntegerField(default=0)
    users = models.ManyToManyField(User)


class Rubrik(models.Model):
    name = models.CharField(max_length=100)
    parent_id = models.IntegerField(null=True)
    is_approved = models.IntegerField(default=1)


class Material(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    user = models.ForeignKey(User, default=1)
    description = models.CharField(max_length=2000)
    rating = models.FloatField(default=0)
    TYPES_MATERIAL = (
        ('Book', 'Книга'),
        ('Method', 'Методические указания'),
        ('Ucheb', 'Учебное пособие'),
        ('Article', 'Статья'),
        ('Ref', 'Реферта'),
        ('Esse', 'Эссе'),
        ('Other', 'Другое'),
    )
    type_material = models.CharField(max_length=20, choices=TYPES_MATERIAL)
    rubrik = models.ForeignKey(Rubrik, null=True, on_delete=models.SET_NULL)
    isbn = models.BigIntegerField(null=True)
    tags = models.ManyToManyField(Tags)
    document = models.FileField(default=0)
    is_approved = models.IntegerField(default=0)
    is_app_changed = models.IntegerField(default=0)
    is_deleted = models.IntegerField(default=0)
    group = models.ForeignKey(Access, null=True)


class Collection(models.Model):
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User)
    materials = models.ManyToManyField(Material, null=True)
    is_deleted = models.IntegerField(default=0)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Библиотека информационных ресурсов</title>
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery-ui.js" type="text/javascript" charset="utf-8"></script>
    <script src="/js/my.js"></script>
    <script src="/js/bootstrap-treeview.js"></script>
    <script src="/js/bootstrap.js" type="text/javascript"></script>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
    <link rel="icon" href="../../favicon.ico">
    <link href='/css/roboto.css' rel='stylesheet' type='text/css'>
    <link href="/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/css/jquery-ui.css">
    <link href="/css/jquery.tagit.css" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap-treeview.css" rel="stylesheet" type="text/css">
    <script src="/js/bootstrapValidator.js" type="text/javascript"></script>
    <script src="/js/tag-it.js" type="text/javascript" charset="utf-8"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-mes navbar-custom">
      <div class="container navbar-container container-fluid container-navbar">
        <div class="collapse navbar-collapse item-custom-nav">
          <ul class="nav navbar-nav navbar-custom">
            <li class="item-custom"><a class="item roboto-font" href="{% url 'catalog' %}">Каталог</a></li>
            <li class="item-custom"><a class="item roboto-font" href="{% url 'search_form' %}">Поиск</a></li>
            <li class="item-custom"><a class="item roboto-font" href="{% url 'index' %}">Популярные</a></li>
            <li class="item-custom"><a class="item roboto-font  add-material" href="{% url 'add_material' %}">Добавление материала</a></li>
            {% if user.is_authenticated %}
              <li class="item-custom"><a class="item roboto-font" href="{% url 'lk' %}">Личный кабинет</a></li>
            {% else %}
              <li class="not-reg">
                  <li class="item-reg">
                  <a class="item reg" href="{% url 'login' %}">
                  <span class="glyphicon glyphicon-log-in"></span> Вход</a>
                  </li>
                  <li class="item-reg">
                  <a class="item reg signup" href="{% url 'signup' %}">
                  <span class="glyphicon glyphicon-user"></span> Регистрация</a>
                  </li>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container container-custom">
      <div class="row">
        <div class="col-md-12 col-sm-12">
          {%block content %} {% endblock %}
        </div>
      </div>
    </div>

  </body>
</html>

{% block js %} {% endblock %}

templates/catalog.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron custom-jumbotron catalog-container">
  <div id="tree"></div>
</div>
<button type="button" class="btn btn-success" id="show_cat" data-dismiss="modal">Показать содержимое рубрики</button><br><br>

{%endblock %}

templates/control.html
{% extends "base.html" %}
{% block content %}
<div class="sort-menu">

  {% if user.is_superuser %}
    <a href="/control" class="btn btn-primary admin-panel" role="button">Панель администратора</a>
  {% endif %}
  <a href="/logout" class="btn btn-success admin-panel" role="button">Выход</a>

</div>

<div class="jumbotron custom-jumbotron reg-container-2">
  <a href="{% url 'control_materials_edit' %}" class="btn btn-success panel-lk-admin" role="button">Управление материалами</a>
  <a href="{% url 'control_users' %}" class="btn btn-success panel-lk-admin" role="button">Управление пользователями</a>
  <a href="{% url 'control_rubrik' %}" class="btn btn-success panel-lk-admin" role="button">Управление рубриками</a>
  <a href="{% url 'control_tags' %}" class="btn btn-success panel-lk-admin" role="button">Управление тегами</a>
  <a href="{% url 'control_access' %}" class="btn btn-success panel-lk-admin" role="button">Управление доступом</a>
  <a href="{% url 'control_materials' %}" class="btn btn-success panel-lk-admin" role="button">Модерация материалов</a>

</div>

{%endblock %}

templates/control_edit.html
{% extends "base.html" %}
{% block content %}

<div class="sort-menu">
  {% if user.is_superuser %}
    <a href="/control" class="btn btn-primary admin-panel" role="button">Панель администратора</a>
  {% endif %}
  <a href="/logout" class="btn btn-success admin-panel" role="button">Выход</a>
</div>
<div class="jumbotron custom-jumbotron my-container">
	<div class="active">
		{% if materials  %}
      <p>Активные материалы</p>
			{% for material in materials %}
        {% if material.is_deleted == 0 %}
  				<ul class="list-group list-all-materials" id="{{ material.id }}">
  				  <li class="list-group-item">
  						<a href="/material/{{ material.id }}"><b>{{ material.title }}<b></a>
  						<a href="/lk/edit/{{ material.id }}" class="btn btn-warning admin-edit control-item"
  											role="button">Редактировать</a>
  				  </li>
  				</ul>
        {% endif %}
			{% endfor %}
      <p>Удаленные материалы</p>
			{% for material in materials %}
        {% if material.is_deleted == 1 %}
  				<ul class="list-group list-all-materials" id="{{ material.id }}">
  				  <li class="list-group-item">
  						<a href="/material/{{ material.id }}"><b>{{ material.title }}<b></a>
  						<a href="/lk/edit/{{ material.id }}" class="btn btn-warning admin-edit control-item"
  											role="button">Редактировать</a>
  				  </li>
  				</ul>
        {% endif %}
			{% endfor %}
		{% else %}
		<div class="alert alert-success not-reg" role="alert">Вы пока не добавили ни одного материала</div>
		{% endif %}
	</div>
</div>
{%endblock %}

templates/control_materials.html
{% extends "base.html" %}
{% block content %}

<div class="sort-menu">
  {% if user.is_superuser %}
    <a href="/control" class="btn btn-primary admin-panel" role="button">Панель администратора</a>
  {% endif %}
  <a href="/logout" class="btn btn-success admin-panel" role="button">Выход</a>
</div>
<div class="jumbotron custom-jumbotron my-container">
	<div class="active">
		{% if materials  %}
      <p>Материалы, ожидающие модерадию</p>
			{% for material in materials %}
        {% if material.is_app_changed == 0 %}
  				<ul class="list-group list-all-materials" id="{{ material.id }}">
  				  <li class="list-group-item">
  						<a href="/material/{{ material.id }}"><b>{{ material.title }}<b></a>
  						<a id="approve" status="0" matid="{{ material.id }}" class="btn btn-warning admin-edit control-item"
  											role="button">Отклонить</a>
              <a id="approve" status="1" matid="{{ material.id }}" class="btn btn-success admin-edit control-item"
                        role="button">Одобрить</a>
  				  </li>
  				</ul>
        {% endif %}
			{% endfor %}
      <p>Материалы, не прошедшие модерацию</p>
			{% for material in materials %}
        {% if material.is_app_changed == 1 and material.is_approved == 0 %}
  				<ul class="list-group list-all-materials" id="{{ material.id }}">
  				  <li class="list-group-item">
  						<a href="/material/{{ material.id }}"><b>{{ material.title }}<b></a>
  						<a id="approve" status="0" matid="{{ material.id }}" class="btn btn-default admin-edit control-item"
  											role="button">Отклонено</a>
              <a id="approve" status="1" matid="{{ material.id }}" class="btn btn-success admin-edit control-item"
                        role="button">Одобрить</a>
  				  </li>
  				</ul>
        {% endif %}
			{% endfor %}
      <p>Материалы, успешно прошедшие модерадию</p>
			{% for material in materials %}
        {% if material.is_app_changed == 1 and material.is_approved == 1 %}
  				<ul class="list-group list-all-materials" id="{{ material.id }}">
  				  <li class="list-group-item">
  						<a href="/material/{{ material.id }}"><b>{{ material.title }}<b></a>
  						<a id="approve" status="0" matid="{{ material.id }}" class="btn btn-warning admin-edit control-item"
  											role="button">Отклонить</a>
              <a id="approve" status="1" matid="{{ material.id }}" class="btn btn-default admin-edit control-item"
                        role="button">Одобрено</a>
  				  </li>
  				</ul>
        {% endif %}
			{% endfor %}
		{% else %}
		<div class="alert alert-success not-reg" role="alert">На модерации пока нет материалов</div>
		{% endif %}
	</div>
</div>
{%endblock %}

templates/control_users.html
{% extends "base.html" %}
{% block content %}

<div class="sort-menu">
  {% if user.is_superuser %}
    <a href="/control" class="btn btn-primary admin-panel" role="button">Панель администратора</a>
  {% endif %}
  <a href="/logout" class="btn btn-success admin-panel" role="button">Выход</a>
</div>
<div class="jumbotron custom-jumbotron my-container">
	<div class="active">
		{% if users  %}
      <p>Список пользователей</p>
			{% for user in users %}
  				<ul class="list-group list-all-materials" id="{{ material.id }}">
  				  <li class="list-group-item">
  						<b>{{ user.username }}<b></a>
  						{% if user.is_active == True %}
                <a id="block_user" typeb="0" userid="{{ user.id }}" class="btn btn-warning admin-edit control-item"
  											role="button">Заблокировать</a>
              {% else %}
                <a id="block_user" typeb="1" userid="{{ user.id }}" class="btn btn-danger admin-edit control-item"
                        role="button">Разблокировать</a>
              {% endif %}
  				  </li>
  				</ul>
			{% endfor %}
		{% else %}
		<div class="alert alert-success not-reg" role="alert">Список пользователей пуст</div>
		{% endif %}
	</div>
</div>
{%endblock %}

templates/create_group.html
{% extends "base.html" %}
{% block content %}
  <div class="sort-menu">

    {% if user.is_superuser %}
      <a href="/control" class="btn btn-primary admin-panel" role="button">Панель администратора</a>
    {% endif %}
    <a href="/logout" class="btn btn-success admin-panel" role="button">Выход</a>

  </div>

  <div class="jumbotron custom-jumbotron reg-container-2">
    <h2>Создание группы доступа</h2>
    <form id="group-form" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for f in form.visible_fields %}
        <div class="form-group {% if f.errors %}has-error{% endif %}" >
          <label for="{{ f.id_for_label }}">{{ f.label }} </label>
            {{ f }}
        </div>
      {% endfor %}
        <button id="btn-group-create" type="submit" class="btn btn-primary">Создать группу доступа</button><br>
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
      {% if error %}
        <br>
        <div class="alert alert-danger" role ="alert" id="field-error">{{ error }}</div>
      {% endif %}
    </form>
    <!-- Modal -->
    <div id="users_dialog" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Выберите пользователей</h4>
          </div>
          <div class="modal-body">
            {% for user in users %}
              <ul class="list-group list-all-materials" id="{{ collection.id }}">
                <li class="list-group-item">
                  <a id="{{ user.id }}" href=""><b>{{ user.username }}<b></a>
                  <a id="add_user" userid="{{ user.id }}" class="btn btn-success admin-edit control-item"
                            role="button">Выбрать пользователя</a>
                </li>
              </ul>
            {% endfor %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            <button id="save_users" type="button" class="btn btn-primary" data-dismiss="modal">Сохранить</button>
          </div>
        </div>

      </div>
    </div>
  </div>

{%endblock %}

templates/denied.html
{% extends "base.html" %}
{% block content %}

	 <div class="jumbotron custom-jumbotron-materials">
            <div class="alert alert-danger" role ="alert" id="field-error">
            У вас нет доступа к этому материалу</div>
 </div>

{%endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
	 <div class="sort-menu">
		 <h3 class="film-sort">Отсортировать по</h3>
		 <a href="/" class="btn btn-success btn-sort" role="button">Рейтингу</a>
		 <a href="/popular" class="btn btn-default" role="button">Популярности</a>
		 <a href="/title" class="btn btn-default" role="button">Названию</a>
		 {% if user.is_superuser %}
		   <a href="/control" class="btn btn-primary admin-panel" role="button">Панель администратора</a>
		 {% endif %}
	 </div>

	 <div class="jumbotron custom-jumbotron">
		 <!-- <h1>Рекомендованые материалы</h1> -->
		  {% for material in materials %}
			 	<div class="panel panel-default">
				  <div class="panel-body">
						<a href="/material/{{ material.id }}" class="title-link">
							<h4>{{ material.title }}</h4>
						</a>
				  </div>
				</div>
		  {% endfor %}
 </div>

{%endblock %}

templates/lk.html
{% extends "base.html" %}
{% block content %}
<div class="sort-menu">

  {% if user.is_superuser %}
    <a href="/control" class="btn btn-primary admin-panel" role="button">Панель администратора</a>
  {% endif %}
  <a href="/logout" class="btn btn-success admin-panel" role="button">Выход</a>

</div>

<div class="jumbotron custom-jumbotron reg-container-2">
  <a href="{% url 'my' %}" class="btn btn-success panel-lk" role="button">Мои материалы</a>
  <a href="{% url 'collections' %}" class="btn btn-success panel-lk" role="button">Коллекции материалов</a>
  <!-- <a href="" class="btn btn-success panel-lk" role="button">Оценки</a> -->

</div>

{%endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="col-md-8 col-sm-8 col-md-offset-2">
    <div class="jumbotron reg-container">
	    <h2>Вход</h2>
	    <form id="log-form" action="/login/" method="post" enctype="multipart/form-data">
	     	{% csrf_token %}
	     	{% for f in form.visible_fields %}
	        <div class="form-group {% if f.errors %}has-error{% endif %}" >
	        	<label for="{{ f.id_for_label }}">{{ f.label }} </label>
	        	  {{ f }}
	        </div>
        {% endfor %}
	        <button id="btn-log" type="submit" class="btn btn-primary">Вход</button><br>
        {% if error %}
          <br>
          <div class="alert alert-danger" role ="alert" id="field-error">{{ error }}</div>
        {% endif %}
	    </form>
    </div>
  </div>
</div>

{%endblock %}

templates/material.html
{% extends "base.html" %}
{% block content %}

	 <div class="jumbotron custom-jumbotron-materials">
			 	<div class="panel panel-default">
				  <div class="panel-body">
							<b>Название материала</b>
							{% if user.is_authenticated %}
								<button id="add_to_col" type="button" class="btn btn-warning admin-panel" data-toggle="modal" data-target="#myModal">
										Добавить в коллекцию</button>
									{% if material.user == user or user.is_superuser %}
										<a href="/lk/edit/{{ material.id }}" class="btn btn-warning admin-panel"
															role="button">Редактировать</a>
									{% endif %}
									{% if material.user == user or user.is_superuser %}
										{% if material.is_approved == 0 and material.is_app_changed = 0 %}
											<a id="approve" status="0" matid="{{ material.id }}" class="btn btn-warning admin-panel"
																role="button">Отклонить</a>
											<a id="approve" status="1" matid="{{ material.id }}" class="btn btn-success admin-panel"
																role="button">Одобрить</a>
										{% elif material.is_approved == 1 and material.is_app_changed = 1 %}
											<a id="approve" status="0" matid="{{ material.id }}" class="btn btn-warning admin-panel"
																role="button">Отклонить</a>
											<a id="approve" status="1" matid="{{ material.id }}" class="btn btn-default admin-panel"
																role="button">Одобрено</a>
										{% elif material.is_approved == 0 and material.is_app_changed = 1 %}
											<a id="approve" status="0" matid="{{ material.id }}" class="btn btn-default admin-panel"
																role="button">Отклонено</a>
											<a id="approve" status="1" matid="{{ material.id }}" class="btn btn-success admin-panel"
																role="button">Одобрить</a>
										{% endif %}
									{% endif %}
							{% endif %}
							<h4>{{ material.title }} </h4>
              <b>Автор</b><h4>
                <a  class="title-link"> {{ material.author }}</a></h4>
							<b>Тип материала</b> <h4>{{ material.get_type_material_display }} </h4>
							<b>Рубрика</b>
							<h4>
								<a href="/search/{{ material.rubrik.name }}" class="title-link">
									{{ material.rubrik.name }}
							 	</a>
							</h4>
							{% if material.isbn %}
								<b>ISBN</b> <h4>{{ material.isbn }} </h4>
							{% endif %}
              <b>Теги</b>
                 <h4> {% for tag in material.tags.all %}
                    <a href="/searchtag/{{ tag.tag }}" class="title-link"> {{ tag.tag }}</a>
                      {% endfor %}
                </h4>
							<b>Описание</b> <h4>{{ material.description }} </h4>
							<b>Документ</b> <h4>{{ material.document.name|slice:"2:" }} </h4>
							<a href="{{ material.document.url }}" class="btn btn-success"
												role="button" download>Скачать</a>
							<!-- Modal -->
							<div id="myModal" class="modal fade" role="dialog">
							  <div class="modal-dialog">

							    <!-- Modal content-->
							    <div class="modal-content">
							      <div class="modal-header">
							        <button type="button" class="close" data-dismiss="modal">&times;</button>
							        <h4 class="modal-title">Выберите в какую коллекцию добавить материал</h4>
							      </div>
							      <div class="modal-body">
											{% for collection in collections %}
												<ul class="list-group list-all-materials" id="{{ collection.id }}">
													<li class="list-group-item">
														<input type="hidden" id="collection_id" value="{{ collection.id }}">
														<input type="hidden" id="material_id" value="{{ material.id }}">
														<a href="/collections/{{ collection.id }}"><b>{{ collection.title }}<b></a>
														<a id="add_to" colid="{{ collection.id }}"class="btn btn-success admin-edit control-item"
																			role="button">Выбрать коллекцию</a>
													</li>
												</ul>
											{% endfor %}
							      </div>
							      <div class="modal-footer">
							        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
							      </div>
							    </div>

							  </div>
							</div>

				  </div>
				</div>
 </div>

{%endblock %}

templates/my.html
{% extends "base.html" %}
{% block content %}

<div class="sort-menu">
  {% if user.is_superuser %}
    <a href="/control" class="btn btn-primary admin-panel" role="button">Панель администратора</a>
  {% endif %}
  <a href="/logout" class="btn btn-success admin-panel" role="button">Выход</a>
</div>
<div class="jumbotron custom-jumbotron my-container">
	<div class="active">
		{% if materials  %}
      <p>Активные материалы</p>
			{% for material in materials %}
        {% if material.is_deleted == 0 %}
  				<ul class="list-group list-all-materials" id="{{ material.id }}">
  				  <li class="list-group-item">
  						<a href="/material/{{ material.id }}"><b>{{ material.title }}<b></a>
  						<a href="/lk/edit/{{ material.id }}" class="btn btn-warning admin-edit control-item"
  											role="button">Редактировать</a>
  				  </li>
  				</ul>
        {% endif %}
			{% endfor %}
      <p>Удаленные материалы</p>
			{% for material in materials %}
        {% if material.is_deleted == 1 %}
  				<ul class="list-group list-all-materials" id="{{ material.id }}">
  				  <li class="list-group-item">
  						<a href="/material/{{ material.id }}"><b>{{ material.title }}<b></a>
  						<a href="/lk/edit/{{ material.id }}" class="btn btn-warning admin-edit control-item"
  											role="button">Редактировать</a>
  				  </li>
  				</ul>
        {% endif %}
			{% endfor %}
		{% else %}
		<div class="alert alert-success not-reg" role="alert">Вы пока не добавили ни одного материала</div>
		{% endif %}
	</div>
</div>
{%endblock %}

templates/signup.html
{% extends "base.html" %}
{% block content %}

  <div class="col-md-8 col-sm-8 col-md-offset-2">
    <div class="jumbotron reg-container">
	    <h2>Регистрация</h2>
	    <form id="reg-form" action="/signup/" method="post" enctype="multipart/form-data">
	     	{% csrf_token %}
	     	{% for f in form.visible_fields %}
	        <div class="form-group {% if f.errors %}has-error{% endif %}" >
	        	<label for="{{ f.id_for_label }}">{{ f.label }} </label>
	        	  {{ f }}
	        </div>
        {% endfor %}
	        <button id="btn-sbmt" type="submit" class="btn btn-primary">Зарегистрироваться</button><br>
        {% if error %}
          <br>
          <div class="alert alert-danger" role ="alert" id="field-error">{{ error }}</div>
        {% endif %}
	    </form>
    </div>
  </div>

{%endblock %}